language: php
sudo: false
php:
  - "5.4"
  - "5.5"
  - "5.6"
before_script:
  - curl http://getcomposer.org/installer | php
  - php composer.phar install
install: composer install
script:
  - vendor/bin/phpcs --standard=PSR2 -p --ignore=vendor,examples .
  - vendor/bin/phpunit
